# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: lizitime.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:

  - Name: Org1
    Domain: org1.lizitime.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: Org2
    Domain: org2.lizitime.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

