
version: '2'

services:

  ca0:
    container_name: ca_peerOrg1
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.lizitime.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/132856f17c9a32b9f6c8818f50e0ad01d629988a2b436018e0a6c4191b5b0a75_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.lizitime.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/132856f17c9a32b9f6c8818f50e0ad01d629988a2b436018e0a6c4191b5b0a75_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.lizitime.com/ca/:/etc/hyperledger/fabric-ca-server-config

  peer0.org1.lizitime.com:
    container_name: peer0.org1.lizitime.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.lizitime.com
    extra_hosts:
      - "orderer.lizitime.com:192.168.31.140"

  cli:
    container_name: cli
    extends:
      file:  base/cli-base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ADDRESS=peer0.org1.lizitime.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.lizitime.com/peers/peer0.org1.lizitime.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.lizitime.com/peers/peer0.org1.lizitime.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.lizitime.com/peers/peer0.org1.lizitime.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.lizitime.com/users/Admin@org1.lizitime.com/msp
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    depends_on:
      - peer0.org1.lizitime.com
    extra_hosts:
      - "orderer.lizitime.com:192.168.31.140"
