
version: '2'

volumes:
  orderer.liziblockchain.com:
  orderer2.liziblockchain.com:
  orderer3.liziblockchain.com:
  # orderer4.liziblockchain.com:
  # orderer5.liziblockchain.com:

# networks:
#   beqt:

services:

  orderer.liziblockchain.com:
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    container_name: orderer.liziblockchain.com
    # networks:
    #   - beqt
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer.liziblockchain.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer.liziblockchain.com/tls/:/var/hyperledger/orderer/tls
        # - orderer.liziblockchain.com:/var/hyperledger/production/orderer
    ports:
    - 7050:7050


  orderer2.liziblockchain.com:
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    container_name: orderer2.liziblockchain.com
    # networks:
    # - beqt
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer2.liziblockchain.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer2.liziblockchain.com/tls/:/var/hyperledger/orderer/tls
        # - orderer2.liziblockchain.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.liziblockchain.com:
    extends:
      file: base/orderer-base.yaml
      service: orderer-base
    container_name: orderer3.liziblockchain.com
    # networks:
    # - beqt
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer3.liziblockchain.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer3.liziblockchain.com/tls/:/var/hyperledger/orderer/tls
        # - orderer3.liziblockchain.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  # orderer4.liziblockchain.com:
  #   extends:
  #     file: base/orderer-base.yaml
  #     service: orderer-base
  #   container_name: orderer4.liziblockchain.com
  #   # networks:
  #   # - beqt
  #   volumes:
  #       - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
  #       - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer4.liziblockchain.com/msp:/var/hyperledger/orderer/msp
  #       - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer4.liziblockchain.com/tls/:/var/hyperledger/orderer/tls
  #       # - orderer4.liziblockchain.com:/var/hyperledger/production/orderer
  #   ports:
  #   - 10050:7050


  # orderer5.liziblockchain.com:
  #   extends:
  #     file: base/orderer-base.yaml
  #     service: orderer-base
  #   container_name: orderer5.liziblockchain.com
  #   # networks:
  #   # - beqt
  #   volumes:
  #       - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
  #       - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer5.liziblockchain.com/msp:/var/hyperledger/orderer/msp
  #       - ./crypto-config/ordererOrganizations/liziblockchain.com/orderers/orderer5.liziblockchain.com/tls/:/var/hyperledger/orderer/tls
  #       # - orderer5.liziblockchain.com:/var/hyperledger/production/orderer
  #   ports:
  #   - 11050:7050
