
version: '2'

volumes:
  ca0.liziblockchain.com:
  peer0.org1.liziblockchain.com:
  cli.liziblockchain.com:

services:

  ca0.liziblockchain.com:
    container_name: ca_peerOrg1
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.liziblockchain.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/cc14916ada153c7dacbbad79dbc2e50a98249bf3e41e002a1194adef04152823_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.liziblockchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/cc14916ada153c7dacbbad79dbc2e50a98249bf3e41e002a1194adef04152823_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.liziblockchain.com/ca/:/etc/hyperledger/fabric-ca-server-config

  peer0.org1.liziblockchain.com:
    container_name: peer0.org1.liziblockchain.com
    extends:
      file:  base/peer-base.yaml
      service: peer0.org1.liziblockchain.com
    extra_hosts:
      - "orderer.liziblockchain.com:192.168.3.1"

  cli.liziblockchain.com:
    container_name: cli
    extends:
      file:  base/cli-base.yaml
      service: cli-base
    environment:
      - CORE_PEER_ADDRESS=peer0.org1.liziblockchain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.liziblockchain.com/peers/peer0.org1.liziblockchain.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.liziblockchain.com/peers/peer0.org1.liziblockchain.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.liziblockchain.com/peers/peer0.org1.liziblockchain.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.liziblockchain.com/users/Admin@org1.liziblockchain.com/msp
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    depends_on:
      - peer0.org1.liziblockchain.com
    extra_hosts:
      - "orderer.liziblockchain.com:192.168.3.1"
