---
name: lizibase-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.example.com
    - peer1.org1.example.com
    certificateAuthorities:
    - ca.org1.example.com
peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICSDCCAe+gAwIBAgIQTrhS4SA5v0K2FESsgMSo7zAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDAyMDQxMzI3MDlaFw0zMDAyMDExMzI3
        MDlaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAE106Xd/ItM++Ii3kPdkWqc8BlmQ2E3pk5eG89S25Hc5d46+yoWl1iDZzc
        3R0nMXw2sXhV8qkaRG8Z6LQMUDgDm6NfMF0wDgYDVR0PAQH/BAQDAgGmMA8GA1Ud
        JQQIMAYGBFUdJQAwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgoTWTldJ/o2Yf
        oRuBqzW7km52ff8TZ1HqDdM4a7QPmfcwCgYIKoZIzj0EAwIDRwAwRAIgfp17c5tV
        PncZq6lRxBek/TsfTk0XnqMH3NkvDn7WkI0CIEGDn2z/TttunMKPwk4xFb8471x1
        9BLRE46RHbpoNQmZ
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com
  peer1.org1.example.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICSDCCAe+gAwIBAgIQTrhS4SA5v0K2FESsgMSo7zAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEfMB0GA1UEAxMWdGxz
        Y2Eub3JnMS5leGFtcGxlLmNvbTAeFw0yMDAyMDQxMzI3MDlaFw0zMDAyMDExMzI3
        MDlaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBvcmcxLmV4YW1wbGUuY29tMR8wHQYD
        VQQDExZ0bHNjYS5vcmcxLmV4YW1wbGUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAE106Xd/ItM++Ii3kPdkWqc8BlmQ2E3pk5eG89S25Hc5d46+yoWl1iDZzc
        3R0nMXw2sXhV8qkaRG8Z6LQMUDgDm6NfMF0wDgYDVR0PAQH/BAQDAgGmMA8GA1Ud
        JQQIMAYGBFUdJQAwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgoTWTldJ/o2Yf
        oRuBqzW7km52ff8TZ1HqDdM4a7QPmfcwCgYIKoZIzj0EAwIDRwAwRAIgfp17c5tV
        PncZq6lRxBek/TsfTk0XnqMH3NkvDn7WkI0CIEGDn2z/TttunMKPwk4xFb8471x1
        9BLRE46RHbpoNQmZ
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org1.example.com
      hostnameOverride: peer1.org1.example.com
certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICQzCCAeqgAwIBAgIRAIoEFqQSFeh0BGYs5tnruUQwCgYIKoZIzj0EAwIwczEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
        Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjAwMjA0MTMyNzA5WhcNMzAwMjAxMTMyNzA5
        WjBzMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMN
        U2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQb3JnMS5leGFtcGxlLmNvbTEcMBoGA1UE
        AxMTY2Eub3JnMS5leGFtcGxlLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
        BCd51HMUCHGfD81O74A2x3l5yYN0UOUacSj3HxYHwyCFQ/xjmduTJC9SNy50syfr
        gyAaTc7cNwVs7At1m/37c9ejXzBdMA4GA1UdDwEB/wQEAwIBpjAPBgNVHSUECDAG
        BgRVHSUAMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIC90WlixBLaIXencv2YK
        VuiK+Sn5sC27oal1FJnRd/voMAoGCCqGSM49BAMCA0cAMEQCIF43tfXIDXwD15qc
        71PLcltcnVNkXWhBh5e+YLs2o/MgAiAtFar1JzWliUrNtjxXum9peQukoj50DQVM
        JmOaDbLsBg==
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
   
