---
name: lizibase-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.lizitime.com
    - peer1.org1.lizitime.com
    certificateAuthorities:
    - ca.org1.lizitime.com
peers:
  peer0.org1.lizitime.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWzCCAgKgAwIBAgIRAL1T8IwTf8STzGGwjgvYY0AwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMSAwHgYDVQQDExd0
        bHNjYS5vcmcxLmxpeml0aW1lLmNvbTAeFw0yMDAyMTMxMzUxMDBaFw0zMDAyMTAx
        MzUxMDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFvcmcxLmxpeml0aW1lLmNvbTEg
        MB4GA1UEAxMXdGxzY2Eub3JnMS5saXppdGltZS5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAATB7rMXqvnBSHyUGuvndPW9fTdC/6E1wbLtxmyxsL0pWqqUY8lB
        Om7wBJ+XmSeNRtwHuz+fCiVgzxLzE/wNk3Wvo20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIKoKdGj+8oTFKzBq7fPOvaFlL8ZHtfY7ZdgAgFhciM/sMAoGCCqG
        SM49BAMCA0cAMEQCICo6dJK8fIqUZuQfXvcsHk7S8vy+p3iIPfGAkpUDXzYrAiAH
        xJXssDu+kahEVUU4AlKy56kxMwedI3ZWic3A5nUgqA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.lizitime.com
      hostnameOverride: peer0.org1.lizitime.com
  peer1.org1.lizitime.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWzCCAgKgAwIBAgIRAL1T8IwTf8STzGGwjgvYY0AwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMSAwHgYDVQQDExd0
        bHNjYS5vcmcxLmxpeml0aW1lLmNvbTAeFw0yMDAyMTMxMzUxMDBaFw0zMDAyMTAx
        MzUxMDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFvcmcxLmxpeml0aW1lLmNvbTEg
        MB4GA1UEAxMXdGxzY2Eub3JnMS5saXppdGltZS5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAATB7rMXqvnBSHyUGuvndPW9fTdC/6E1wbLtxmyxsL0pWqqUY8lB
        Om7wBJ+XmSeNRtwHuz+fCiVgzxLzE/wNk3Wvo20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIKoKdGj+8oTFKzBq7fPOvaFlL8ZHtfY7ZdgAgFhciM/sMAoGCCqG
        SM49BAMCA0cAMEQCICo6dJK8fIqUZuQfXvcsHk7S8vy+p3iIPfGAkpUDXzYrAiAH
        xJXssDu+kahEVUU4AlKy56kxMwedI3ZWic3A5nUgqA==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org1.lizitime.com
      hostnameOverride: peer1.org1.lizitime.com
certificateAuthorities:
  ca.org1.lizitime.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVDCCAfugAwIBAgIQIHe2ytbXXM0QFrki6Gz2gjAKBggqhkjOPQQDAjB1MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEaMBgGA1UEChMRb3JnMS5saXppdGltZS5jb20xHTAbBgNVBAMTFGNh
        Lm9yZzEubGl6aXRpbWUuY29tMB4XDTIwMDIxMzEzNTEwMFoXDTMwMDIxMDEzNTEw
        MFowdTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcT
        DVNhbiBGcmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMR0wGwYD
        VQQDExRjYS5vcmcxLmxpeml0aW1lLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABDbLY+e2psKV2qSVr7AkMEvwZ/5KRqdN2h1CgAXsh6O9dQ2bvcuWOrIulcnl
        ebvVjCkfNDQIqjj0BcZz5wZ/RGyjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUE
        FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4E
        IgQgzBSRatoVPH2su61528LlCpgkm/PkHgAqEZSt7wQVKCMwCgYIKoZIzj0EAwID
        RwAwRAIgCjUHTExj6StNtTx0gaSLWfVoM8OztYHyKNJIuh2gV7QCIFZ0FOihC5uN
        wtm7n8250+N1i53Q3weZYaNaZ2WGXJsz
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
   
