---
name: lizibase-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.lizitime.com
    - peer1.org1.lizitime.com
    certificateAuthorities:
    - ca.org1.lizitime.com
peers:
  peer0.org1.lizitime.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWjCCAgKgAwIBAgIRAPekEwnydKSAizQGJOmvL3IwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMSAwHgYDVQQDExd0
        bHNjYS5vcmcxLmxpeml0aW1lLmNvbTAeFw0yMDAyMDkwOTU2MDBaFw0zMDAyMDYw
        OTU2MDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFvcmcxLmxpeml0aW1lLmNvbTEg
        MB4GA1UEAxMXdGxzY2Eub3JnMS5saXppdGltZS5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAAQovtyvaQVF5nAbjxlT0NTUzIri9l4uWLCIFv4X3Hz2OUktvypb
        w+vRFQXovI7mqebY58RQXb8MC0htySnmep3+o20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIPAUTUvyw2RzS7xJ9H5X0kbuMduP+VtunP1ZrXR94/SJMAoGCCqG
        SM49BAMCA0YAMEMCIEM37OyOSCTqRqlcXOijbaKhN6sBOj82ePcs0YrwSbFkAh8g
        F+4wh0g/dWxh+40x2Dn2+OrTs+dsZCh7NKRCN/sJ
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.org1.lizitime.com
      hostnameOverride: peer0.org1.lizitime.com
  peer1.org1.lizitime.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWjCCAgKgAwIBAgIRAPekEwnydKSAizQGJOmvL3IwCgYIKoZIzj0EAwIweDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMSAwHgYDVQQDExd0
        bHNjYS5vcmcxLmxpeml0aW1lLmNvbTAeFw0yMDAyMDkwOTU2MDBaFw0zMDAyMDYw
        OTU2MDBaMHgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYD
        VQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQKExFvcmcxLmxpeml0aW1lLmNvbTEg
        MB4GA1UEAxMXdGxzY2Eub3JnMS5saXppdGltZS5jb20wWTATBgcqhkjOPQIBBggq
        hkjOPQMBBwNCAAQovtyvaQVF5nAbjxlT0NTUzIri9l4uWLCIFv4X3Hz2OUktvypb
        w+vRFQXovI7mqebY58RQXb8MC0htySnmep3+o20wazAOBgNVHQ8BAf8EBAMCAaYw
        HQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8w
        KQYDVR0OBCIEIPAUTUvyw2RzS7xJ9H5X0kbuMduP+VtunP1ZrXR94/SJMAoGCCqG
        SM49BAMCA0YAMEMCIEM37OyOSCTqRqlcXOijbaKhN6sBOj82ePcs0YrwSbFkAh8g
        F+4wh0g/dWxh+40x2Dn2+OrTs+dsZCh7NKRCN/sJ
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.org1.lizitime.com
      hostnameOverride: peer1.org1.lizitime.com
certificateAuthorities:
  ca.org1.lizitime.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICVDCCAfugAwIBAgIQKAQpcNkqVm9lv57Yx7KuZzAKBggqhkjOPQQDAjB1MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEaMBgGA1UEChMRb3JnMS5saXppdGltZS5jb20xHTAbBgNVBAMTFGNh
        Lm9yZzEubGl6aXRpbWUuY29tMB4XDTIwMDIwOTA5NTYwMFoXDTMwMDIwNjA5NTYw
        MFowdTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcT
        DVNhbiBGcmFuY2lzY28xGjAYBgNVBAoTEW9yZzEubGl6aXRpbWUuY29tMR0wGwYD
        VQQDExRjYS5vcmcxLmxpeml0aW1lLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABCyLG5XYGy8J6fsMmh9f1oHCEgnOvBW07XQtDgceHop4ma64EBPGPjwkeUu2
        sCVTfZLsyioSCB4BgStCEWzBYBOjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUE
        FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4E
        IgQgEyhW8XyaMrn2yIGPUOCtAdYpmIorQ2AY4KbEGRtbCnUwCgYIKoZIzj0EAwID
        RwAwRAIgKymQPYP58vYD+qRysYBHqwWvx6JFdh6hNhWrIePBgU0CIAJNVlqFZjHu
        z4mRFwDwCAxtJAEnWJT4qyF6hFczEAlD
        -----END CERTIFICATE-----
        
    httpOptions:
      verify: false
   
